#!bin/sh
# What it does:
# Here is script to change all footer of the html file. 
# The content of all *.html files is changes which
# have the Tags AUTOGENERATED FOOTER POSITION/START/STOP in them.

find ../help/ -name "*.html" | xargs sed -i -f changeFooter.sed 
